image: $CI_IMAGE

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - lint
    - build
    - test

flake8:
    stage: lint
    script:
        - flake8 .

eslint:
    stage: lint
    script:
        - cd pipeline_manager/frontend
        - npm install
        - npm run lint

build-project:
    stage: build
    script:
        - ./build

pytest:
    stage: test
    script:
        - python3 -m pytest
