image: $CI_IMAGE

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - lint
    - build
    - deploy

flake8:
    stage: lint
    script:
        - flake8 .

eslint:
    stage: lint
    script:
        - cd pipeline_manager/frontend
        - npm install
        - npm run lint

build:
    stage: build
    script:
        - ./build
        - tar cf $CI_DOCS_ARCHIVE -C pipeline_manager/frontend/dist/ .
    artifacts:
        paths:
            - $CI_DOCS_ARCHIVE

pytest:
    stage: build
    script:
        - python3 -m pytest

deploy:
    image: $CI_DOCS_DOCKER_IMAGE
    stage: deploy
    dependencies:
        - build
    variables:
        GIT_STRATEGY: none
    tags:
        - docs
    script: echo 'Deploying pipeline manager page'
    artifacts:
        paths:
            - $CI_DOCS_ARCHIVE
