image: $CI_IMAGE

variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - lint
    - build

flake8:
    stage: lint
    script:
        - flake8 .
    allow_failure: false

eslint:
    stage: lint
    script:
        - cd pipeline_manager/frontend
        - npm install --only=dev
        - npm run lint
    allow_failure: false

build-project:
    stage: build
    script:
        - ./build
    allow_failure: false
